name: Build

on:
  push:
    branches: [main]
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Build for macOS
        if: runner.os == 'macOS'
        run: dart compile exe lib/commitflow.dart -o commitflow-${{ runner.os }}

      - name: Build for Linux
        if: runner.os == 'Linux'
        run: dart compile exe lib/commitflow.dart -o commitflow-${{ runner.os }}

      - name: Build for Windows
        if: runner.os == 'Windows'
        run: dart compile exe lib/commitflow.dart -o commitflow-${{ runner.os }}.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: commitflow-artifacts
          path: |
            commitflow-${{ runner.os }}
            commitflow-${{ runner.os }}
            commitflow-${{ runner.os }}.exe