name: Build

on:
  push:
    branches: [main]
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sdk: ${{ matrix.sdk }}

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Print PATH
        run: echo $PATH

      - name: Install dependencies
        run: dart pub get

      - name: Build for multiple platforms
        run: |
          docker run --rm -v "$(pwd):/app" -w "/app" google/dart:2.15.0 bash -c "dart compile exe lib/main.dart -o commitflow-linux"
          docker run --rm -v "$(pwd):/app" -w "/app" -e DART_VM_OPTIONS="--enable-isolate-groups" apple/dart:2.15.0 bash -c "dart compile exe lib/main.dart -o commitflow-macos"
          docker run --rm -v "$(pwd):/app" -w "/app" mcr.microsoft.com/dotnet/sdk:6.0-focal bash -c "apt-get update && apt-get install -y clang libc6-dev-i386 && dart compile exe lib/main.dart -o commitflow-windows.exe"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: commitflow-artifacts
          path: |
            commitflow-macos
            commitflow-linux
            commitflow-windows.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Build for multiple platforms
        run: |
          docker run --rm -v "$(pwd):/app" -w "/app" google/dart:2.15.0 bash -c "dart compile exe lib/main.dart -o commitflow-linux"
          docker run --rm -v "$(pwd):/app" -w "/app" -e DART_VM_OPTIONS="--enable-isolate-groups" apple/dart:2.15.0 bash -c "dart compile exe lib/main.dart -o commitflow-macos"
          docker run --rm -v "$(pwd):/app" -w "/app" mcr.microsoft.com/dotnet/sdk:6.0-focal bash -c "apt-get update && apt-get install -y clang libc6-dev-i386 && dart compile exe lib/main.dart -o commitflow-windows.exe"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: commitflow-release-artifacts-${{ github.event.release.tag_name }}
          path: |
            commitflow-macos-${{ github.event.release.tag_name }}
            commitflow-linux-${{ github.event.release.tag_name }}
            commitflow-windows-${{ github.event.release.tag_name }}.exe